#!/bin/bash -ex

# modify these paths for your system
YAML_SRC_DIR=
YAML_INSTALL_DIR=

cmake $YAML_SRC_DIR \
-DCMAKE_C_COMPILER:FILEPATH=mpicc \
-DCMAKE_CXX_COMPILER:FILEPATH=mpicxx \
-DCMAKE_INSTALL_PREFIX:PATH=$YAML_INSTALL_DIR \
-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DYAML_CPP_BUILD_TOOLS:BOOL=OFF \
2>&1 | tee config_log
