#include "goal_dimension.hpp"

namespace goal {

PHX_DIM_TAG_IMPLEMENTATION(Elem)
PHX_DIM_TAG_IMPLEMENTATION(Node)
PHX_DIM_TAG_IMPLEMENTATION(Dim)
PHX_DIM_TAG_IMPLEMENTATION(IP)
PHX_DIM_TAG_IMPLEMENTATION(Dummy)

}  // namespace goal
