#include "goal_dimension.hpp"

namespace goal {

PHX_DIM_TAG_IMPLEMENTATION(Ent)
PHX_DIM_TAG_IMPLEMENTATION(Node)
PHX_DIM_TAG_IMPLEMENTATION(Dim)
PHX_DIM_TAG_IMPLEMENTATION(IP)
PHX_DIM_TAG_IMPLEMENTATION(Dummy)

} // end namespace goal
